# Generated by Django 2.0.1 on 2018-03-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('job_category', models.CharField(max_length=250)),
                ('job_location', models.CharField(max_length=250)),
            ],
        ),
    ]
